### ISSUE TITLE
まずはRender.com上にデプロイ

### ISSUE THREAD

**Issue by notwo** [notwo/youknowFrontend#1]
- [静的サイトのデプロイ](https://ja.vitejs.dev/guide/static-deploy.html#render)
- [Deploy a Vue.js App](https://render.com/docs/deploy-vue-js)

**Comment by notwo** [comment]
そのままデプロイしようとしたら以下warning
```
Sep 11 11:09:12 PM  warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```

[package-lock.jsonとyarn.lockが共存しているときの解決方法](https://zenn.dev/mo_ri_regen/articles/package-lock-yarn-lock)
によればpackage-lock.jsonが悪さしてるとのこと。
プラスで、手元のnode_modulesを削除する

それもありそうだが手元の環境だとnpmを使っているがyarnに切り替えたほうが良さそう

**Comment by notwo** [comment]
```
Sep 19 07:56:23 AM  error @vitejs/plugin-vue@4.3.4: The engine "node" is incompatible with this module. Expected version "^14.18.0 || >=16.0.0". Got "14.17.0"
```
Expected version~~の部分からするにrender.com上のnodeのバージョンが古い(14.17.0)のが原因

参考：[package.jsonとpackage-lock.jsonのバージョン指定や必要性について](https://qiita.com/sasao3/items/b794c1e44715bb6f834f)

解決法は[Using Node 18 but its telling me my node version is 14.7](https://community.render.com/t/using-node-18-but-its-telling-me-my-node-version-is-14-7/10637/2)の通り、render.comの環境変数NODE_VERSIONに14.18.0以上を指定する

因みに手元のNodeバージョンは
```
$ node -v
v20.5.0
```
となっている

**Comment by notwo** [comment]
# 手元の環境にyarnを入れる
[yarnをインストールする](https://qiita.com/suisui654/items/1b89446e03991c7c2c3d)に従ってyarnを入れる

```
$ yarn init
yarn init v1.22.19
error An unexpected error occurred: "Can't answer a question unless a user TTY".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\XXXX\\Desktop\\work\\youknowFrontend\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/init for documentation about this command.
(env1)
```
というエラーが出た

この時点でのyarnのバージョン
```
$ yarn -v
1.22.19
(env1)
```

Can't answer a question unless a user TTYが気になったので確かめてみた
```
$ node
Welcome to Node.js v20.5.0.
Type ".help" for more information.
> process.stdout.isTTY
true
```
こっちは問題なさそう


[yarn initでエラーが出た場合の対処方法](https://qiita.com/buchiya4th/items/f312bf2a7a7a6dd28f58)を試してみる

```
$ yarn add yarn
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
error An unexpected error occurred: "EBUSY: resource busy or locked, open 'C:\\Users\\XXXX\\Desktop\\work\\youknowFrontend\\package.json'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\XXXX\\Desktop\\work\\youknowFrontend\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
(env1)
```

[[Unity] resource busy or lockedがでてきてPackageManagerがインストールできない](https://qiita.com/mikene_koko/items/4ac6381650008bbb8b2a)の通りVSCodeを閉じたらできた
```
$ yarn add yarn
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ yarn@1.22.19
info All dependencies
└─ yarn@1.22.19
Done in 0.49s.
(env1)
```
その後yarn initしても変わらず

[Yarn fails under git-bash: Can't answer a question unless a user TTY](https://github.com/yarnpkg/yarn/issues/4497)によるとGit Bashが良くない可能性・・・？
=>[alancnet commented on Jun 7, 2019](https://github.com/yarnpkg/yarn/issues/4497#issuecomment-499615665)でも言われているがNPMが動くのにYarnが動かないので別のツールに頼るのは違うでしょ、という意見には完全同意。でも動かないので他のコメントから解決法を探すことにする


[GuyARoss commented on Nov 6, 2020](https://github.com/yarnpkg/yarn/issues/4497#issuecomment-722711897)の通りに以下コマンドを実行してようやく解決した
```
$ yarn set version berry
➤ YN0000: Retrieving https://repo.yarnpkg.com/3.6.3/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.6.3.cjs
➤ YN0000: Done in 2s 21ms
(env1)
```

```
$ yarn init
{
  name: 'youknowFrontend',
  packageManager: 'yarn@3.6.3'
}
(env1)
```

今度はyarnのバージョンも変わっている
```
$ yarn -v
3.6.3
(env1)
```

berryに関しては[yarnをv1からv2(Berry)へ移行する](https://zenn.dev/kkoudev/articles/5b440e1e341458)

**Comment by notwo** [comment]
ビルドが通って
```
Sep 19 08:18:15 AM  ==> Running 'yarn start'
Sep 19 08:18:17 AM  yarn run v1.22.5
Sep 19 08:18:18 AM  error Command "start" not found.
```

package.jsonのscriptsにstartが定義されていないのが原因
とはいえ何を書けばいいか分からないので調査
=>そもそもチュートリアルでもstartコマンドの記述がなく例にも当然見当たらない。でもログ上ではyarn startされていてそれが原因で落ちているので意味不明な状態

**Comment by notwo** [comment]
うまくいかないのはrender.com上でweb serviceにしていたからだった。
static siteに直してデプロイ

今度は
```
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
```
とか出た
調べる限りyarn installすればいいはずだがやっても特に差分が出ず直らない

手詰まりだったのでいっそのことyarn.lockを消してみた
するとうまくいく。いや何でだよ・・・

https://you-know-frontend.onrender.com/ にアクセスしたらちゃんと入れたのでデプロイ自体は成功している
yarn.lockを今後作成してもおそらく落ちるだろうと思われるため、yarn.lockは敢えてpushしないしそもそも作らない方向で行く
=> yarn run devは通らなくなる
```
Internal Error: you_know_vue@workspace:.: This package doesn't seem to be present in your lockfil       e; run "yarn install" to update the lockfile
    at V0.getCandidates (C:\Users\07k11\Desktop\work\youknowFrontend\.yarn\releases\yarn-3.6.3.cj       s:435:5145)
    at kf.getCandidates (C:\Users\07k11\Desktop\work\youknowFrontend\.yarn\releases\yarn-3.6.3.cj       s:391:1264)
    at C:\Users\07k11\Desktop\work\youknowFrontend\.yarn\releases\yarn-3.6.3.cjs:439:8033
    at df (C:\Users\07k11\Desktop\work\youknowFrontend\.yarn\releases\yarn-3.6.3.cjs:390:11070)
    at ge (C:\Users\07k11\Desktop\work\youknowFrontend\.yarn\releases\yarn-3.6.3.cjs:439:8013)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 0)
    at async io (C:\Users\07k11\Desktop\work\youknowFrontend\.yarn\releases\yarn-3.6.3.cjs:390:10       398)
    at async C:\Users\07k11\Desktop\work\youknowFrontend\.yarn\releases\yarn-3.6.3.cjs:439:8545
    at async ti.startProgressPromise (C:\Users\07k11\Desktop\work\youknowFrontend\.yarn\releases\       yarn-3.6.3.cjs:390:47579)
```
でもnpm run devとかビルドはできるので問題ない(そもそもビルドは本番でしかやらない)

**Comment by notwo** [comment]
完了したのでclose
