### ISSUE TITLE
render.comのエラー対応

### ISSUE THREAD

**Issue by notwo** [notwo/youknowFrontend#84]
<details>
<summary>エラー内容</summary>

```
==> Running build command 'yarn; yarn build'...
yarn install v1.22.21
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
error @vitejs/plugin-vue@4.5.1: The engine "node" is incompatible with this module. Expected version "^14.18.0 || >=16.0.0". Got "14.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn run v1.22.21
$ vite build
failed to load config from /opt/render/project/src/vite.config.js
error during build:
Error: Cannot find module 'node:url'
Require stack:
- /opt/render/project/src/vite.config.js
- /opt/render/project/src/node_modules/vite/dist/node/chunks/dep-bb8a8339.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/render/project/src/vite.config.js:35:23)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object._require.extensions.<computed> [as .js] (file:///opt/render/project/src/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66340:24)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
==> Build failed 😞
```
</details>

**Comment by notwo** [comment]
```
error @vitejs/plugin-vue@4.5.1: The engine "node" is incompatible with this module. Expected version "^14.18.0 || >=16.0.0". Got "14.17.0"
```
から、nodeのバージョンが古いのが原因で落ちているらしい
render.com上のnodeバージョンを上げてやれば解決しそう

**Comment by notwo** [comment]
以下の通りビルド成功したのでclose

<details>
<summary>実行内容</summary>

```
$ vite build
vite v4.5.1 building for production...
transforming...
✓ 203 modules transformed.
rendering chunks...
computing gzip size...
dist/index.html                               0.88 kB │ gzip:  0.51 kB
dist/assets/SearchForm-ec28f69b.css           0.65 kB │ gzip:  0.35 kB
dist/assets/ScrollToTopButton-c104a5ff.css    1.75 kB │ gzip:  0.63 kB
dist/assets/index-752f515b.css                1.89 kB │ gzip:  0.72 kB
dist/assets/CategoryList-efeebf28.css         1.89 kB │ gzip:  0.69 kB
dist/assets/LibraryList-8c716098.css          1.98 kB │ gzip:  0.72 kB
dist/assets/KeywordList-129a152f.css          2.17 kB │ gzip:  0.75 kB
dist/assets/KeywordDetail-367f3cb2.css        2.88 kB │ gzip:  0.83 kB
dist/assets/Tooltip-4de08f09.css              3.37 kB │ gzip:  0.81 kB
dist/assets/Callback-1e162f21.js              0.17 kB │ gzip:  0.18 kB
dist/assets/404-7949da32.js                   0.18 kB │ gzip:  0.17 kB
dist/assets/Top-a7130ec0.js                   0.59 kB │ gzip:  0.52 kB
dist/assets/Libraries-dbdb3863.js             1.04 kB │ gzip:  0.64 kB
dist/assets/Categories-78991469.js            1.07 kB │ gzip:  0.65 kB
dist/assets/Keywords-4af3df4e.js              1.09 kB │ gzip:  0.67 kB
dist/assets/SearchForm-e264479c.js            1.91 kB │ gzip:  1.22 kB
dist/assets/ScrollToTopButton-f353d00f.js     2.21 kB │ gzip:  0.93 kB
dist/assets/Tooltip-bd238032.js               5.18 kB │ gzip:  1.57 kB
dist/assets/LibraryList-8e362438.js           7.34 kB │ gzip:  2.70 kB
dist/assets/KeywordDetail-145f0ff7.js         7.75 kB │ gzip:  2.73 kB
dist/assets/CategoryList-cbb772d7.js          8.15 kB │ gzip:  2.86 kB
dist/assets/KeywordList-83e247a9.js           8.49 kB │ gzip:  2.95 kB
dist/assets/util-7d98146b.js                 15.91 kB │ gzip:  5.67 kB
dist/assets/apis-d73b4814.js                 31.23 kB │ gzip: 12.21 kB
dist/assets/index-7d474e8d.js               127.99 kB │ gzip: 47.32 kB
✓ built in 3.49s
Done in 4.03s.
==> Uploading build...
==> Your site is live 🎉
```
</details>
